# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiouvPkKzlAOmfuLS0KRgp6U9leUHmRg
"""

num=int(input("enter a number:"))
if num%2==0:
  print("Even")
else:
  print("odd")

num=int(input("enter the number"))
if num>0:
  print(num,"is a positive number")
elif num<0:
  print(num,"is a negative number")
else:
  print(num,"is zero")

import math
n=int(input("enter the number"))
result=math.sqrt(n)
print("square root of",n,"is:",result)

def print_string_separately():
    input_string = input("Enter a string: ")

    for char in input_string:
        print(char)

print_string_separately()

def strings_together():
  string1=input("enter the string:")
  string2=input("enter the string:")

  print(  string1 + " " + string2)

strings_together()

num_string=(input("enter a number:"))
num_reversed=num_string[::-1]
print(num_reversed)

#slicing

def print_natural_numbers(n):
    for i in range(1, n + 1):
        print(i)

n = 10
print_natural_numbers(n)